server:
  port: 9003

spring:
  application:
    name: orderservice

eureka:
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka
    register-with-eureka: true
    fetch-registry: true 