server:
  port: 9002

spring:
  application:
    name: notificationservice
  data:
    mongodb:
      uri: mongodb://mongodb:27017/jewelry_db
      database: jewelry_db

eureka:
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka
    register-with-eureka: true
    fetch-registry: true 