server:
  port: 9002

spring:
  application:
    name: notificationservice

eureka:
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka
    register-with-eureka: true
    fetch-registry: true 