server:
  port: 8080

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: userservice
          uri: http://userservice:9001
          predicates:
            - Path=/api/users/**

        - id: orderservice
          uri: http://orderservice:9003
          predicates:
            - Path=/api/orders/**
            - Path=/api/v1/orders/**

        - id: productservice
          uri: http://productservice:9004
          predicates:
            - Path=/api/products/**

        - id: cartservice
          uri: http://cartservice:9005
          predicates:
            - Path=/api/cart/**

        - id: notificationservice
          uri: http://notificationservice:9002
          predicates:
            - Path=/api/notifications/**
      
        - id: paymentservice
          uri: http://paymentservice:9006
          predicates:
            - Path=/api/payments/**

        - id: chatservice
          uri: http://chatservice:9007
          predicates:
            - Path=/api/chat/**

        - id: reviewservice
          uri: http://reviewservice:9008
          predicates:
            - Path=/api/reviews/**


      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
              - "http://frontend:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discoveryserver:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG
    reactor.netty.http.server: DEBUG
