server:
  port: 8080

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/users/**
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/api/v1/orders/**
        - id: productservice
          uri: lb://productservice
          predicates:
            - Path=/api/v1/products/**
        - id: notificationservice
          uri: lb://notificationservice
          predicates:
            - Path=/api/v1/notifications/**
        # - id: chatservice
        #   uri: lb://chatservice
        #   predicates:
        #     - Path=/api/v1/chats/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discoveryserver:8761/eureka
